config/routes.rb
Rails.application.routes.draw do
  resources :performances
  resources :businesses
  #devise_for :users

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/performance.rb
class Performance < ApplicationRecord
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_performance, only: [:show, :edit, :update, :destroy]

  # GET /performances
  # GET /performances.json
  def index
    @performances = Performance.all
  end

  # GET /performances/1
  # GET /performances/1.json
  def show
  end

  # GET /performances/new
  def new
    @performance = Performance.new
  end

  # GET /performances/1/edit
  def edit
  end

  # POST /performances
  # POST /performances.json
  def create
    @performance = Performance.new(performance_params)

    respond_to do |format|
      if @performance.save
        format.html { redirect_to @performance, notice: 'Performance was successfully created.' }
        format.json { render :show, status: :created, location: @performance }
      else
        format.html { render :new }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performances/1
  # PATCH/PUT /performances/1.json
  def update
    respond_to do |format|
      if @performance.update(performance_params)
        format.html { redirect_to @performance, notice: 'Performance was successfully updated.' }
        format.json { render :show, status: :ok, location: @performance }
      else
        format.html { render :edit }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performances/1
  # DELETE /performances/1.json
  def destroy
    @performance.destroy
    respond_to do |format|
      format.html { redirect_to performances_url, notice: 'Performance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance
      @performance = Performance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def performance_params
      params.require(:performance).permit(:business_cd, :plan, :performance, :user_id, :date)
    end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<%= form_for(performance) do |f| %>
  <% if performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(performance.errors.count, "error") %> prohibited this performance from being saved:</h2>

      <ul>
      <% performance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_cd %>
    <%= f.text_field :business_cd %>
  </div>

  <div class="field">
    <%= f.label :plan %>
    <%= f.number_field :plan %>
  </div>

  <div class="field">
    <%= f.label :performance %>
    <%= f.number_field :performance %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performances/edit.html.erb
<h1>Editing Performance</h1>

<%= render 'form', performance: @performance %>

<%= link_to 'Show', @performance %> |
<%= link_to 'Back', performances_path %>

app/views/performances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Performances</h1>

<table>
  <thead>
    <tr>
      <th>Business cd</th>
      <th>Plan</th>
      <th>Performance</th>
      <th>User</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td><%= performance.business_cd %></td>
        <td><%= performance.plan %></td>
        <td><%= performance.performance %></td>
        <td><%= performance.user_id %></td>
        <td><%= performance.date %></td>
        <td><%= link_to 'Show', performance %></td>
        <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
        <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performance', new_performance_path %>|
<%= link_to 'Back', home_index_path %>

app/views/performances/new.html.erb
<h1>New Performance</h1>

<% @performance.user_id = current_user.id %>
<% @performance.date = Date.today.strftime('%Y%m%d') %>

<%= render 'form', performance: @performance %>

<%= link_to 'Back', performances_path %>

app/views/performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business cd:</strong>
  <%= @performance.business_cd %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @performance.plan %>
</p>

<p>
  <strong>Performance:</strong>
  <%= @performance.performance %>
</p>

<p>
  <strong>User:</strong>
  <%= @performance.user_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @performance.date %>
</p>

<%= link_to 'Edit', edit_performance_path(@performance) %> |
<%= link_to 'Back', performances_path %>